name: 'Hello World Action'
description: 'A simple action that prints Hello World'
inputs:
  myInput:
    description: 'An example input'
    required: false
    default: 'World'
runs:
  using: composite
  steps:
    - name: Run script
      shell: bash
      run: |
        echo "Hello ${{ inputs.myInput }}"
